// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iDrqmUdQP7zpZncXuMwzX5
// Component: 4_G_bUJWQioD
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: iDrqmUdQP7zpZncXuMwzX5/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 4_G_bUJWQioD/css
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: noBazM8K9o3/icon
import Line2Icon from "./icons/PlasmicIcon__Line2"; // plasmic-import: fL_vqOgHXMV/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: dWF_kTxjAwQ/icon
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: tT1SvyjnheK/icon
import Vector5Icon from "./icons/PlasmicIcon__Vector5"; // plasmic-import: JsRj0Q0wDz3/icon
import Vector6Icon from "./icons/PlasmicIcon__Vector6"; // plasmic-import: y6fEJ1fFx6J/icon
import Vector7Icon from "./icons/PlasmicIcon__Vector7"; // plasmic-import: zAAcxaxnooA/icon
import Vector8Icon from "./icons/PlasmicIcon__Vector8"; // plasmic-import: tsaCMwLlX5B/icon
import Group32Icon from "./icons/PlasmicIcon__Group32"; // plasmic-import: uObhsT-L5fB/icon
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: M-r17N0RHgJ/icon
import Ellipse6Icon from "./icons/PlasmicIcon__Ellipse6"; // plasmic-import: 1FShYwP_8Q4/icon
import Vector9Icon from "./icons/PlasmicIcon__Vector9"; // plasmic-import: ZTEyLdOLyMJ/icon
import Line6Icon from "./icons/PlasmicIcon__Line6"; // plasmic-import: C45L36blNv9/icon
import Vector10Icon from "./icons/PlasmicIcon__Vector10"; // plasmic-import: MLumEIcStUN/icon
import Ellipse11Icon from "./icons/PlasmicIcon__Ellipse11"; // plasmic-import: Ps5uP8aPdeb/icon
import Ellipse13Icon from "./icons/PlasmicIcon__Ellipse13"; // plasmic-import: M15dzPg-4fA/icon
import Ellipse12Icon from "./icons/PlasmicIcon__Ellipse12"; // plasmic-import: 2VG_iUl_Jfz/icon
import Ellipse14Icon from "./icons/PlasmicIcon__Ellipse14"; // plasmic-import: kUH5TCdbCPs/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: vy6oohth4ZP/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"dashboard"}
            data-plasmic-override={overrides.dashboard}
            className={classNames(projectcss.all, sty.dashboard)}
          >
            {false ? (
              <div
                data-plasmic-name={"repeatGrid11"}
                data-plasmic-override={overrides.repeatGrid11}
                className={classNames(projectcss.all, sty.repeatGrid11)}
              />
            ) : null}

            <VectorIcon
              className={classNames(projectcss.all, sty.svg__gWgRk)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___6I5Mj
              )}
            >
              {"John Drossos"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kiH6
              )}
            >
              {"Internet Marketer, CEO"}
            </div>

            <h6
              data-plasmic-name={"h6"}
              data-plasmic-override={overrides.h6}
              className={classNames(
                projectcss.all,
                projectcss.h6,
                projectcss.__wab_text,
                sty.h6
              )}
              onKeyPress={""}
            >
              {"Website"}
            </h6>

            <div
              data-plasmic-name={"group62"}
              data-plasmic-override={overrides.group62}
              className={classNames(projectcss.all, sty.group62)}
            />

            <Line2Icon
              className={classNames(projectcss.all, sty.svg__aBswS)}
              role={"img"}
            />

            <Vector3Icon
              className={classNames(projectcss.all, sty.svg__llh24)}
              role={"img"}
            />

            <Vector4Icon
              className={classNames(projectcss.all, sty.svg__auyBz)}
              role={"img"}
            />

            <Vector5Icon
              className={classNames(projectcss.all, sty.svg___5AiSo)}
              role={"img"}
            />

            <Vector6Icon
              className={classNames(projectcss.all, sty.svg__j2T2)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bscbp
              )}
            >
              {"Looks Like Things Could Work Better."}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__sugr
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {"Results were not as expected, visit "}
                </React.Fragment>
                <p.PlasmicLink
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.link
                  )}
                  component={Link}
                  href={"dccz.com"}
                  platform={"nextjs"}
                >
                  {"console helper"}
                </p.PlasmicLink>
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>

            {true ? (
              <p.PlasmicImg
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"365px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blank_project/images/group85.svg",
                  fullWidth: 415.115,
                  fullHeight: 341.731,
                  aspectRatio: 1.216374
                }}
              />
            ) : null}

            <div
              data-plasmic-name={"group87"}
              data-plasmic-override={overrides.group87}
              className={classNames(projectcss.all, sty.group87)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cDTv0
                )}
              >
                {"Components"}
              </div>

              <div
                data-plasmic-name={"rectangle147"}
                data-plasmic-override={overrides.rectangle147}
                className={classNames(projectcss.all, sty.rectangle147)}
              />

              <div
                data-plasmic-name={"rectangle154"}
                data-plasmic-override={overrides.rectangle154}
                className={classNames(projectcss.all, sty.rectangle154)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zl3I
                )}
              >
                {"Personal Notes"}
              </div>

              <div
                data-plasmic-name={"rectangle131"}
                data-plasmic-override={overrides.rectangle131}
                className={classNames(projectcss.all, sty.rectangle131)}
              />

              <div
                data-plasmic-name={"rectangle153"}
                data-plasmic-override={overrides.rectangle153}
                className={classNames(projectcss.all, sty.rectangle153)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4VDbT
                )}
              >
                {"Configure Reporter"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pxsUf
                )}
              >
                {"Configure Logic"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rasOi
                )}
              >
                {"Hi! I am your console reporter I will report what you ask"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yQiB9
                )}
              >
                {"myNotebook"}
              </div>

              <div
                data-plasmic-name={"group86"}
                data-plasmic-override={overrides.group86}
                className={classNames(projectcss.all, sty.group86)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__titu6
                  )}
                >
                  {"Marketing"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v4Muo
                  )}
                >
                  {"Calculators"}
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle150"}
                data-plasmic-override={overrides.rectangle150}
                className={classNames(projectcss.all, sty.rectangle150)}
              />

              <div
                data-plasmic-name={"rectangle151"}
                data-plasmic-override={overrides.rectangle151}
                className={classNames(projectcss.all, sty.rectangle151)}
              />

              <div
                data-plasmic-name={"rectangle152"}
                data-plasmic-override={overrides.rectangle152}
                className={classNames(projectcss.all, sty.rectangle152)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__axKyu
                )}
              >
                {"ASK"}
              </div>

              <div
                data-plasmic-name={"image4"}
                data-plasmic-override={overrides.image4}
                className={classNames(projectcss.all, sty.image4)}
              />

              <div
                data-plasmic-name={"group9"}
                data-plasmic-override={overrides.group9}
                className={classNames(projectcss.all, sty.group9)}
              >
                <Vector7Icon
                  className={classNames(projectcss.all, sty.svg__zvu)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"rectangle3"}
                  data-plasmic-override={overrides.rectangle3}
                  className={classNames(projectcss.all, sty.rectangle3)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"rectangle88"}
              data-plasmic-override={overrides.rectangle88}
              className={classNames(projectcss.all, sty.rectangle88)}
            />

            <div
              data-plasmic-name={"rectangle87"}
              data-plasmic-override={overrides.rectangle87}
              className={classNames(projectcss.all, sty.rectangle87)}
            />

            <div
              data-plasmic-name={"strategy"}
              data-plasmic-override={overrides.strategy}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.strategy
              )}
            >
              {" Strategy"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pS5B8
              )}
            >
              {"Results"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kKaqk
              )}
            >
              {"Timeframe"}
            </div>

            <div
              data-plasmic-name={"rectangle86"}
              data-plasmic-override={overrides.rectangle86}
              className={classNames(projectcss.all, sty.rectangle86)}
            />

            <Vector8Icon
              className={classNames(projectcss.all, sty.svg__pgX8T)}
              role={"img"}
            />

            <div
              data-plasmic-name={"rectangle8"}
              data-plasmic-override={overrides.rectangle8}
              className={classNames(projectcss.all, sty.rectangle8)}
            />

            <div
              data-plasmic-name={"rectangle11"}
              data-plasmic-override={overrides.rectangle11}
              className={classNames(projectcss.all, sty.rectangle11)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qsQoH
              )}
            >
              {"My Plan A"}
            </div>

            <Group32Icon
              className={classNames(projectcss.all, sty.svg__xRhBc)}
              role={"img"}
            />

            <Line5Icon
              className={classNames(projectcss.all, sty.svg___13BsS)}
              role={"img"}
            />

            <Ellipse6Icon
              className={classNames(projectcss.all, sty.svg__qapv3)}
              role={"img"}
            />

            <Vector9Icon
              className={classNames(projectcss.all, sty.svg__xXiRk)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group77"}
              data-plasmic-override={overrides.group77}
              className={classNames(projectcss.all, sty.group77)}
            >
              <Vector8Icon
                className={classNames(projectcss.all, sty.svg__bVa6T)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle9"}
                data-plasmic-override={overrides.rectangle9}
                className={classNames(projectcss.all, sty.rectangle9)}
              />

              <div
                data-plasmic-name={"rectangle12"}
                data-plasmic-override={overrides.rectangle12}
                className={classNames(projectcss.all, sty.rectangle12)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hQKg6
                )}
              >
                {"My Plan B"}
              </div>

              <Vector9Icon
                className={classNames(projectcss.all, sty.svg__cuXU)}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"line5"}
              data-plasmic-override={overrides.line5}
              className={classNames(projectcss.all, sty.line5)}
            >
              {false ? (
                <Line5Icon
                  className={classNames(projectcss.all, sty.svg__yqsGy)}
                  role={"img"}
                />
              ) : null}
            </div>

            <div
              data-plasmic-name={"group89"}
              data-plasmic-override={overrides.group89}
              className={classNames(projectcss.all, sty.group89)}
            >
              <div
                data-plasmic-name={"group90"}
                data-plasmic-override={overrides.group90}
                className={classNames(projectcss.all, sty.group90)}
              >
                <div
                  data-plasmic-name={"group91"}
                  data-plasmic-override={overrides.group91}
                  className={classNames(projectcss.all, sty.group91)}
                >
                  <Line6Icon
                    className={classNames(projectcss.all, sty.svg__z0KOk)}
                    role={"img"}
                  />

                  <Ellipse6Icon
                    className={classNames(projectcss.all, sty.svg__yg1Rh)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"group66"}
              data-plasmic-override={overrides.group66}
              className={classNames(projectcss.all, sty.group66)}
            >
              <Vector8Icon
                className={classNames(projectcss.all, sty.svg__gh4XE)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle10"}
                data-plasmic-override={overrides.rectangle10}
                className={classNames(projectcss.all, sty.rectangle10)}
              />

              <div
                data-plasmic-name={"line6"}
                data-plasmic-override={overrides.line6}
                className={classNames(projectcss.all, sty.line6)}
              >
                {false ? (
                  <Line5Icon
                    className={classNames(projectcss.all, sty.svg__k5KmX)}
                    role={"img"}
                  />
                ) : null}
              </div>
            </div>

            <div
              data-plasmic-name={"group88"}
              data-plasmic-override={overrides.group88}
              className={classNames(projectcss.all, sty.group88)}
            >
              <Vector8Icon
                className={classNames(projectcss.all, sty.svg__rfpRn)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle13"}
                data-plasmic-override={overrides.rectangle13}
                className={classNames(projectcss.all, sty.rectangle13)}
              />

              <div
                data-plasmic-name={"line7"}
                data-plasmic-override={overrides.line7}
                className={classNames(projectcss.all, sty.line7)}
              >
                {false ? (
                  <Line5Icon
                    className={classNames(projectcss.all, sty.svg__l7Ccn)}
                    role={"img"}
                  />
                ) : null}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cnjWe
              )}
            >
              {"Loss Reported: -$1200"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dHin
              )}
            >
              {"12/3/2023  -   Today"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___6VPfW
              )}
            >
              {"Showing Pure Profit"}
            </div>

            <Vector10Icon
              className={classNames(projectcss.all, sty.svg__qUjkJ)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wHvK2
              )}
            >
              {"$"}
            </div>

            <Ellipse11Icon
              className={classNames(projectcss.all, sty.svg__m4O9)}
              role={"img"}
            />

            <Ellipse13Icon
              className={classNames(projectcss.all, sty.svg__xhDxu)}
              role={"img"}
            />

            <Ellipse12Icon
              className={classNames(projectcss.all, sty.svg__smrNi)}
              role={"img"}
            />

            <Ellipse14Icon
              className={classNames(projectcss.all, sty.svg___5YINf)}
              role={"img"}
            />

            {true ? (
              <div
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                className={classNames(projectcss.all, sty.freeBox)}
              >
                <div
                  data-plasmic-name={"rectangle84"}
                  data-plasmic-override={overrides.rectangle84}
                  className={classNames(projectcss.all, sty.rectangle84)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sna3R
                    )}
                  >
                    {"https://johndrossos.eu"}
                  </div>

                  <Vector2Icon
                    className={classNames(projectcss.all, sty.svg__pFGP)}
                    role={"img"}
                  />
                </div>
              </div>
            ) : null}
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "dashboard",
    "repeatGrid11",
    "h6",
    "group62",
    "link",
    "img",
    "group87",
    "rectangle147",
    "rectangle154",
    "rectangle131",
    "rectangle153",
    "group86",
    "rectangle150",
    "rectangle151",
    "rectangle152",
    "image4",
    "group9",
    "rectangle3",
    "rectangle88",
    "rectangle87",
    "strategy",
    "rectangle86",
    "rectangle8",
    "rectangle11",
    "group77",
    "rectangle9",
    "rectangle12",
    "line5",
    "group89",
    "group90",
    "group91",
    "group66",
    "rectangle10",
    "line6",
    "group88",
    "rectangle13",
    "line7",
    "freeBox",
    "rectangle84"
  ],

  dashboard: [
    "dashboard",
    "repeatGrid11",
    "h6",
    "group62",
    "link",
    "img",
    "group87",
    "rectangle147",
    "rectangle154",
    "rectangle131",
    "rectangle153",
    "group86",
    "rectangle150",
    "rectangle151",
    "rectangle152",
    "image4",
    "group9",
    "rectangle3",
    "rectangle88",
    "rectangle87",
    "strategy",
    "rectangle86",
    "rectangle8",
    "rectangle11",
    "group77",
    "rectangle9",
    "rectangle12",
    "line5",
    "group89",
    "group90",
    "group91",
    "group66",
    "rectangle10",
    "line6",
    "group88",
    "rectangle13",
    "line7",
    "freeBox",
    "rectangle84"
  ],

  repeatGrid11: ["repeatGrid11"],
  h6: ["h6"],
  group62: ["group62"],
  link: ["link"],
  img: ["img"],
  group87: [
    "group87",
    "rectangle147",
    "rectangle154",
    "rectangle131",
    "rectangle153",
    "group86",
    "rectangle150",
    "rectangle151",
    "rectangle152",
    "image4",
    "group9",
    "rectangle3"
  ],

  rectangle147: ["rectangle147"],
  rectangle154: ["rectangle154"],
  rectangle131: ["rectangle131"],
  rectangle153: ["rectangle153"],
  group86: ["group86"],
  rectangle150: ["rectangle150"],
  rectangle151: ["rectangle151"],
  rectangle152: ["rectangle152"],
  image4: ["image4"],
  group9: ["group9", "rectangle3"],
  rectangle3: ["rectangle3"],
  rectangle88: ["rectangle88"],
  rectangle87: ["rectangle87"],
  strategy: ["strategy"],
  rectangle86: ["rectangle86"],
  rectangle8: ["rectangle8"],
  rectangle11: ["rectangle11"],
  group77: ["group77", "rectangle9", "rectangle12"],
  rectangle9: ["rectangle9"],
  rectangle12: ["rectangle12"],
  line5: ["line5"],
  group89: ["group89", "group90", "group91"],
  group90: ["group90", "group91"],
  group91: ["group91"],
  group66: ["group66", "rectangle10", "line6"],
  rectangle10: ["rectangle10"],
  line6: ["line6"],
  group88: ["group88", "rectangle13", "line7"],
  rectangle13: ["rectangle13"],
  line7: ["line7"],
  freeBox: ["freeBox", "rectangle84"],
  rectangle84: ["rectangle84"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dashboard: makeNodeComponent("dashboard"),
    repeatGrid11: makeNodeComponent("repeatGrid11"),
    h6: makeNodeComponent("h6"),
    group62: makeNodeComponent("group62"),
    link: makeNodeComponent("link"),
    img: makeNodeComponent("img"),
    group87: makeNodeComponent("group87"),
    rectangle147: makeNodeComponent("rectangle147"),
    rectangle154: makeNodeComponent("rectangle154"),
    rectangle131: makeNodeComponent("rectangle131"),
    rectangle153: makeNodeComponent("rectangle153"),
    group86: makeNodeComponent("group86"),
    rectangle150: makeNodeComponent("rectangle150"),
    rectangle151: makeNodeComponent("rectangle151"),
    rectangle152: makeNodeComponent("rectangle152"),
    image4: makeNodeComponent("image4"),
    group9: makeNodeComponent("group9"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle88: makeNodeComponent("rectangle88"),
    rectangle87: makeNodeComponent("rectangle87"),
    strategy: makeNodeComponent("strategy"),
    rectangle86: makeNodeComponent("rectangle86"),
    rectangle8: makeNodeComponent("rectangle8"),
    rectangle11: makeNodeComponent("rectangle11"),
    group77: makeNodeComponent("group77"),
    rectangle9: makeNodeComponent("rectangle9"),
    rectangle12: makeNodeComponent("rectangle12"),
    line5: makeNodeComponent("line5"),
    group89: makeNodeComponent("group89"),
    group90: makeNodeComponent("group90"),
    group91: makeNodeComponent("group91"),
    group66: makeNodeComponent("group66"),
    rectangle10: makeNodeComponent("rectangle10"),
    line6: makeNodeComponent("line6"),
    group88: makeNodeComponent("group88"),
    rectangle13: makeNodeComponent("rectangle13"),
    line7: makeNodeComponent("line7"),
    freeBox: makeNodeComponent("freeBox"),
    rectangle84: makeNodeComponent("rectangle84"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
